name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - uses: microsoft/setup-msbuild@v1
    - run: python Build.py
    - name: Upload Artifact
      if: github.ref != 'refs/heads/master'
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Build
        path: "Toolbox-Latest.zip"
    - name: Make a release
      if: github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: EXPERIMENTAL_LATEST
        prerelease: true
        title: "Experimental Release"
        files: |
          Toolbox-Latest.zip
